---
title: "Research Projects"
output:
   html_document:
     toc: true
---

***
## **Machine Learning and Programming Projects**
***
### Original Research Proposal
  - **On the inclusion of long-range interactions among molecules in machine learning models**
  - More details [here](https://punitjha.github.io/orp_project.html).

***

### Machine Learning Projects

1. **Ad Hoc Information Retrieval System**: 
    - Using 1400 abstracts of journal articles created an information retrieval system that takes in a query and outputs the top matched abstracts using TF-IDF weights and cosine similarity scores.
    - This project was a part of the ECE 365: Data Science and Engineer course.
    - More details of the project can be found in this repository [here](https://github.com/punitjha/ECE365-Data_Science_and_Engineering/tree/master/NLP_Lab5)

2. **Anomaly Detection and Recommender Systems**:
    - Implemented an anomaly detection algorithm for computer serves  based on the Gaussian model.
    - Implemented the collaborative filtering learning algorithm for a dataset of movie ratings.
     - This project was a part of the Machine learning class by Andrew Ng on Coursera.
    - More details of the project can be found in this repository [here](https://github.com/punitjha/Machine_Learning_Coursera/tree/master/machine-learning-ex8)

***
### Lab Coding Assignments  
 1. **ECE 365: Data Science and Engineering.**
    - **Part-I: Machine Learning**
      - k-Nearest Neighbors, Bayes Classifiers, and Linear Discriminant Analysis. [[Link]](https://github.com/punitjha/ECE365-Data_Science_and_Engineering/blob/master/Lab2_vvv/punit2_lab2.ipynb)
      - Naive Bayes, Logistic Regression, and Support Vector Machines. [[Link]](https://github.com/punitjha/ECE365-Data_Science_and_Engineering/blob/master/Lab3_vvv/punit2_lab3.ipynb)
      - K-means clustering, Vector Quantization, Nearest Neighbors Classification, and Linear Regression. [[Link]](https://github.com/punitjha/ECE365-Data_Science_and_Engineering/blob/master/Lab4_vvv/punit2_lab4.ipynb)
      - Eigendecomposition, Singular Value Decomposition, and Principal Component Analysis.
[[Link]](https://github.com/punitjha/ECE365-Data_Science_and_Engineering/blob/master/Lab5_vvv/punit2_lab5.ipynb)
    - **Part-II: Natural Language Processing**
      - Text processing and regular expressions, word frequencies and language, manipulate corpora and plot insightful graphs. [[Link]](https://github.com/punitjha/ECE365-Data_Science_and_Engineering/blob/master/NLP_Lab1/punit2/Lab1/punit2.ipynb)
      - Tokenization, bag-of-words represenation, ogistic regression classifier (discriminative model) using PyTorch.
[[Link]](https://github.com/punitjha/ECE365-Data_Science_and_Engineering/blob/master/NLP_Lab2/punit2/NLPLab2/Lab2_NLP.ipynb) 
      - N-gram model, generate representative sentences, study of the effect of training data size, and language model complexity (n-gram size), on the modeling capacity of a language model.
[[Link]](https://github.com/punitjha/ECE365-Data_Science_and_Engineering/blob/master/NLP_Lab3/punit2/NLPLab3/NLPLab3.ipynb)
      - Count-Based Word Vectors, Co-occurrence_matrix, PCA, plot-embeddings,  Word2Vec Word Embeddings, Cosine Similarity, Polysemous Words, Synonyms & Antonyms, Solving Analogies with Word Vectors, Guided Analysis of Bias in Word Vectors, and Independent Analysis of Bias in Word Vectors. [[Link]](https://github.com/punitjha/ECE365-Data_Science_and_Engineering/blob/master/NLP_Lab4/punit2/Lab4/lab4.ipynb)
    - **Part-III: Text Analysis** 
      - Syntagmatic word association minining.
[[Link]](https://github.com/punitjha/ECE365-Data_Science_and_Engineering/blob/master/Text_Analysis_Lab-1/punit2_lab1.ipynb)
      - Sentiment analysis.
[[Link]](https://github.com/punitjha/ECE365-Data_Science_and_Engineering/blob/master/Text_Analysis_Lab-2/punit2_lab2.ipynb)
      - Document Clustering using TF-IDF vectorizer.
[[Link]](https://github.com/punitjha/ECE365-Data_Science_and_Engineering/blob/master/Text_Analysis_Lab-3/punit2_lab3.ipynb)   
      - Topic Modelling: Use of gensim library to create a LDA topic model.
[[Link]](https://github.com/punitjha/ECE365-Data_Science_and_Engineering/blob/master/Text_Analysis_Lab-4/punit2_lab4.ipynb)
   
   
 2. **Machine Learning by Andrew Ng (Coursera)**
    - Intro to Octave, Linear regression with one variable, Gradient Descent, and Linear regression with multiple variables.[[Link]](https://github.com/punitjha/Machine_Learning_Coursera/tree/master/machine-learning-ex1/ex1)
    - Logistic Regression, Regularized logistic regression, and Plotting the decision boundary. [[Link]](https://github.com/punitjha/Machine_Learning_Coursera/tree/master/machine-learning-ex2/ex2)
    - Multi-class Classification/ One-vs-all Classification and Neural Networks. [[Link]](https://github.com/punitjha/Machine_Learning_Coursera/tree/master/machine-learning-ex3/ex3)
    - Neural Networks, Backpropagation, and Visualizing the hidden layer. [[Link]](https://github.com/punitjha/Machine_Learning_Coursera/tree/master/machine-learning-ex4/ex4)
    - Regularized Linear Regression, Bias-variance and learning curves, Polynomial regression, Adjusting the regularization parameter, Computing test set error, and visualization.
[[Link]](https://github.com/punitjha/Machine_Learning_Coursera/tree/master/machine-learning-ex5/ex5)    
    - Support Vector Machines and Spam Classification. [[Link]](https://github.com/punitjha/Machine_Learning_Coursera/tree/master/machine-learning-ex6/ex6)    
    - K-means Clustering and Image compression with K-means.
[[Link]](https://github.com/punitjha/Machine_Learning_Coursera/tree/master/machine-learning-ex7/ex7)

3. **Coming Soon Assignments from:**
    -  **CS 446: Machine Learning: Theory  (Ongoing)**
    -  **CS 447: Natural Language Processing (Ongoing)**
    -  **CS 498: Intro. to Deep Learning (Ongoing)**
    -  **Data Mining Specialization  - UIUC Coursera (Ongoing)**
    -  **Cloud Computing Specialization  - UIUC Coursera (Ongoing)**
    
***    
    
### Programming Projects


1.  **Design and Implementations of Parallel OpenMP and MPI LU factorization: Application to Finite Difference Method.**
     - In this project, I with my group presented  six different OpenMP and
MPI based parallel algorithms for the LU factorization of dense matrices.
     - Please find the details [here](https://drive.google.com/file/d/1I17RTZGtopQQOAkk9z2MUyQEGYWmYsRN/view?usp=sharing)
     - Codes [here](https://github.com/punitjha/CS_420_Project)
2. **Optimization of a dense matrix-matrix multiplication routine and understanding its performance behavior.** 
   - Parallel programming machine project on dense matrix-matrix multiplication and cache performance.
   - Please find the details [here](https://drive.google.com/file/d/1IvqxqR6E6_CINKB8OunAmBpQvYcb_nPo/view?usp=sharing)
   - Codes [here](https://github.com/punitjha/CS_420_MPs)
3. **Utilization of  multi-core CPU using OpenMP and MPI to implement a dense matrix-matrix multiply (MM) routine and understanding the performance behavior.**
    - Usage of PAPI to measure cache misses and to analyze the performance.
    - Please find the details [here](https://drive.google.com/file/d/1yYzdTwtnV8-4xoFCRmFnWe275Ny0dOx9/view?usp=sharing)
    - Codes [here](https://github.com/punitjha/CS_420_MPs)
4. **Utilization of  multi-core CPU using OpenMP and a GPU using OpenACC to implement a matrix-multiply routine for multiplying a band matrix by a dense matrix.**
   - Investigation of the performance impact of varying the band and matrix size.
   - Please find the details [here](https://drive.google.com/file/d/1Pb781ThU_9EG2uDTm1NB4uaETlWU7GH4/view?usp=sharing)
   - Codes [here](https://github.com/punitjha/CS_420_MPs)
   
***
### Chemistry Programming Projects

1. **Programming projects for [CHEM 548: Molecular Electronic Structure Advanced Quantum Chemistry & Numerical Methods.](http://faculty.scs.illinois.edu/hirata/education.html)**
   - Third Project
     - Hückel and Su-Schrieffer-Heeger band structures for 1D and 2D solids.
     - The report can be found [here](https://drive.google.com/file/d/13CjQVDkpwSTJEk4sAuKDva8kw8z89CHt/view?usp=sharing)
     - Codes can be found [here](https://github.com/punitjha/CHEM_548_Project_3)
   - Second Project
     - Wave packet propagation, phase and group velocities, Ehrenfest theorem, convolution theorem, path integrals.
     - The report can be found [here](https://drive.google.com/file/d/1_XcSwoqlycy-i354jd4TW_kfLtEWTs8P/view?usp=sharing)
     - Codes can be found [here](https://github.com/punitjha/CHEM_548_Project_2)
   - First Project
     - Time-dependent perturbation theory and spectroscopy.
     - The report can be found [here](https://drive.google.com/file/d/1zz3pD4KzFYVm5nen6yhf8u-hqnGXjfF5/view?usp=sharing)
     - Codes can be found [here](https://github.com/punitjha/CHEM_548_Project_1)

2. **Electronic structure theory programming projects. ** 
   - Molecular Geometry Analysis.
     - Instructions  can be found  [here](https://drive.google.com/file/d/1ucsnJL2St-DKmW5cs6o_3M0TKxbly09p/view?usp=sharing)
     - Codes can be found [here](https://github.com/punitjha/Crawdad_Project_4)
   - Harmonic Vibrational Analysis.
     - Instructions  can be found  [here](https://drive.google.com/file/d/1rTu-TCD8vZMX0CsE9NFp1brANDxAqt5x/view?usp=sharing)
     - Codes can be found [here](https://github.com/punitjha/Crawdad_Project_3)
   - The Hartree-Fock Self-Consistent Field Method.
     - Instructions  can be found  [here](https://drive.google.com/file/d/1sIRmEjvBEmPc7N1bsYVXyuu1kVwnSsYz/view?usp=sharing)
     - Codes can be found [here](https://github.com/punitjha/Crawdad_Project_2)
   - The Second-Order Moller-Plesset Perturbation Theory (MP2) Energy.
     - Instructions  can be found  [here](https://drive.google.com/file/d/1zDiOA2GHTFlNxmCZSjk4dJDEQ-xe4-4x/view?usp=sharing)
     - Codes can be found [here](https://github.com/punitjha/Crawdad_Project_1)




***
## **Chemistry Research Projects and Summer Internships**
***
### Ph.D. Research Project 
  - Research conducted at the University of Illinois at Urbana-Champaign, Urbana-Champaign, IL, Aug 2016 - Present. 
     - **Topic**: Finite-temperature many-body perturbation theory.
     - More details [here](https://punitjha.github.io/phd_project.html).
    
***
    
      
### M. Sc. Research Project
- Research conducted at the National Institute of Science Education and Research, Bhubaneswar, India, Aug 2014 - June 2016.
    - **Topic**: Diagonal suppressed constant time Correlation Spectroscopy (COSY).
    - More details [here](https://punitjha.github.io/msc_project.html). 
***

### Research Summer Internships
1. **Undergraduate Summer Intern- 2015**
    - Research conducted at the University of Calgary, Calgary, Canada, May 2015 - Aug 2015.
       - **Topic**: Dynamics of gas-hydrate nucleation.
       -  More details [here](https://punitjha.github.io/calgary.html).
  
2. **Undergraduate Summer Intern- 2014**
     - Research conducted at the Indian Institute of Technology- Bombay, Mumbai, India, May 2014 - Aug 2014.
        - **Topic**: Quantum reactive flux theory.
        - More details [here](https://punitjha.github.io/iit_b.html).
         
      
3.  **Undergraduate Summer Intern- 2013** 
     - Research conducted at the National Institute of Science Education and Research, Bhubaneswar, India, May 2013 - Aug 2013.
         - **Topic**: Reactive molecular dynamics of hydrocarbon dissociation on Ni surface.
         - More details [here](https://punitjha.github.io/niser_summer.html).
          
***    
  <!--   - Reactive molecular dynamics of hydrocarbon dissociation on Ni surface: Carried out reactive dynamics simulations of the adsorption and decomposition of CH\textsubscript{4} molecules interacting with a Ni(100) surface. Studied the temperature dependence of chemisorption of CH\textsubscript{4} by breakage of C-H bonds that leads to the formation of CH\textsubscript{3} and H radical on a Ni(100) surface. -->
  <!-- - **Skills Acquired:** -->
  <!--         Learned rogramming in FORTRAN 90 and how to carry out quantum mechanical simulations using ReaxFF. -->
             
             
             
<!--     - Finite-temperature many-body perturbation theory (FT-MBPT): FT-MBPT is a theory to calculate the thermodynamic parameters of the grand canonical system at a given temperature.  -->
  <!--     - I implemented the $\lambda$-variation method to  calculate the $n$th-order corrections to grand potential and internal energy using the FT-MBPT formalism which showed it is mathematically inconsistent and does not conserve charge.  -->
  <!--     - Derived the correct analytic formulas for FT-MBPT using another ansatz wherein charge was conserved. -->
  <!--     Implemented the FT-MBPT in a canonical ensemble and derived semi-analytic formulas. -->
  <!-- - **Original Research Proposal (ORP)** -->
  <!--       - Developed an ORP on the problem of inclusion of long-range (electrostatic) interactions in machine learning algorithms. Analyzed different neural network schemes,            especially deep high-dimensional neural networks (HDNNs), and whether they can efficiently learn and predict molecular charges learned from various charge partitioning schemes. -->
  <!--     - Studied different charge partitioning schemes like Hirshfeld, Charge Model 5, Merz-Singh-Kollman, and Natural Bonding Orbital methods used in molecular dynamics              simulations. -->
  <!--     - Proposed modifications to mathematical formulation and structure of HDNNs to be able to better predict  molecular charges, computational cost for implementing the            project, potential  setbacks, and alternate plans for the project. -->
  <!-- - **Skills Acquired:** -->
  <!--         Acquired knowledge of \textit{ab initio} and DFT electronic structure methods. Learned about machine learning algorithms. Learned to program in Python and enhanced           my programming skills in C++ and FORTRAN. -->

  <!-- ---     -->
  
  
  
  
  
  <!--   - Diagonal suppressed constant time Correlation Spectroscopy (COSY): Worked on a novel NMR pulse sequence to achieve diagonal suppressed COSY (correlation spectroscopy) spectra with high sensitivity and absorptive cross peak line-shapes.              -->
  <!--   - Carried out simulations and  product operator  calculations for 2, 3, and 4 spin systems using the novel NMR pulse sequence. -->
  <!--   - Implemented various optimization strategies for the pulse sequence that included the addition of water suppression module, removing axial and multiple quantum peaks by using gradient fields, etc.  -->
  <!-- - **Skills Acquired:** -->
  <!--         Acquired programming skills to program in the TopSpin 2.1 programming language and  learned to how to perform 1D, 2D NMR experiments on a 400 MHz spectrometer. -->

  <!-- ---     -->
  
  
   <!-- - Quantum reactive flux theory: Studied the quantum analog of classical non-Markovian Kramers' equation and the phase space distribution function formulation of the method of reactive flux in the memory friction regime. Analyzed quantum Kramers' equation for energy diffusion and barrier crossing dynamics in the high-friction regime. -->
   <!--  - **Skills Acquired:** -->
   <!--        Acquired skills to use Mathematica for solving integrals and numerical analysis. Learned mathematical methods in physics. -->

   <!--   ---   -->
   
<!--      -->
<!--       - Dynamics of gas-hydrate nucleation: Wrote C++  codes to study the probability distribution of lifetime of gas hydrate cages in the molecular dynamics simulation of  incipient hydrates starting from a CH\textsubscript{4}/H\textsubscript{2}S bubble in liquid H\textsubscript{2}O in a 3D box. -->
<!--       - Studied the effect of the different guest gas molecules on the lifetime of these cages. } -->
<!--   - **Skills Acquired:** -->
<!--           Learned about the object-oriented programming features of C++ and its data structures. I also learned the skills -->
<!-- required to create memory-efficient C++ codes. -->

<!--   ---   -->
  
 