---
title: "Useful Links & References"

output:
   html_document:
     toc: true
---

***


## Websites

* [Crash Course Statistics](https://www.youtube.com/playlist?list=PL8dPuuaLjXtNM_Y-bUAhblSAdWRnmBUcr){target="_blank"}
* [Khan Academy Probability and Statistics](https://www.youtube.com/channel/UCRXuOXLW3LcQLWvxbZiIZ0w/featured){target="_blank"}

***

## Deep Learning 

### Courses 
 
* [Stanford CS231n: Convolutional Neural Networks for Visual Recognition](http://cs231n.stanford.edu/)
* [MIT 6.S191: Introduction to Deep Learning](http://introtodeeplearning.com/)
* [Princeton COS 495: Introduction to Deep Learning](https://www.cs.princeton.edu/courses/archive/spring16/cos495/)
* [IDIAP EE559: Deep Learning](https://fleuret.org/ee559/)
* [ENS Deep Learning: Do It Yourself](https://mlelarge.github.io/dataflowr-web/dldiy_ens.html)
* [U of I IE 534: Deep Learning](https://courses.engr.illinois.edu/ie534/fa2019/)
* [Full Stack Deep Learning](https://course.fullstackdeeplearning.com/)

###  Tutorials

*    [Python/numpy tutorial](https://cs231n.github.io/python-numpy-tutorial/)
*    [PyTorch tutorial](https://pytorch.org/tutorials/)
*    [TensorFlow tutorial](https://www.tensorflow.org/tutorials/)

###  Useful textbooks available online

*    [Deep Learning](https://www.deeplearningbook.org/) by I. Goodfellow, Y. Bengio and A. Courville
*    [Dive into Deep Learning](http://d2l.ai/index.html) -- an interactive online book by A. Zhang, Z. Lipton, M. Li and A. Smola from Amazon
*    [Michael Nielsen's online book on Neural Networks and Deep Learning](http://neuralnetworksanddeeplearning.com/)
*    [Hastie, Tibshirani and Friedman, Elements of Statistical Learning](https://web.stanford.edu/~hastie/ElemStatLearn/)
*    [David Forsyth's Applied Machine Learning textbook draft](http://luthuli.cs.uiuc.edu/~daf/courses/AML-18/learning-book-19-April-18.pdf)

***
  
## Podcasts  

* [Data Skeptic](https://dataskeptic.com/) 
* [Data Stories](http://datastori.es/) 
  
***
  
## R Resources

* [A brief tutorial on R (5 pages)](https://d18ky98rnyall9.cloudfront.net/_d4bb66436b3204edbe8c93209dab051c_r_tutorial_spring18.pdf?Expires=1598313600&Signature=fPpq5baGIswe48stD82Qc8xurCAE~TlXCffhaA1uHPkRfm07rYL6e-ALJrp4A9R5ZUJUkIHCbatnn-1FRY3hDfx6Zep4eItWGskSy2oA6J2GXSiwI3~rtMdxAB9EzJ1I12XccvsKPYrrvn8cvg3c5T7w3E3PAUo7ioQ6JE5j-7g_&Key-Pair-Id=APKAJLTNE6QMUY6HBC5A)
* [Examples of the **learnr** package in R](https://rstudio.github.io/learnr/examples.html)
* [Swirl- Learn R, in R.](https://swirlstats.com/)
* [An Introduction to R](http://cran.r-project.org/doc/manuals/r-release/R-intro.html)
* [UCLA-Statistical Computing R resources](https://stats.idre.ucla.edu/r/)
* [Download and Install R - Comprehensive R Archive Network (CRAN) website](https://cran.r-project.org/){target="_blank"}
* [All R Package Documentation from CRAN](https://cran.r-project.org/web/packages/available_packages_by_name.html){target="_blank"}
* [Awesome R](https://awesome-r.com/){target="_blank"}  
* [R-Bloggers](https://www.r-bloggers.com/){target="_blank"}
* [RStudio Cheatsheets](https://www.rstudio.com/resources/cheatsheets/){target="_blank"}
* [Tidyverse](https://www.tidyverse.org/){target="_blank"}  
* [Useful R Packages from RStudio](https://support.rstudio.com/hc/en-us/articles/201057987-Quick-list-of-useful-R-packages){target="_blank"}

  
***  
  
### GitHub Links

* ["Awesome R" Packages](https://github.com/qinwf/awesome-R) 
* ["Bad Data" Guide](https://github.com/Quartz/bad-data-guide) 
* [Create Word Clouds](https://github.com/Lchiffon/wordcloud2) 
* [Data Sharing for Statisticians](https://github.com/jtleek/datasharing){target="_blank"}
* [Deep Learning Papers](https://github.com/terryum/awesome-deep-learning-papers){target="_blank"}
* [Public Datasets](https://github.com/awesomedata/awesome-public-datasets){target="_blank"} 
* [Machine Learning and Deep Learning Tutorials](https://github.com/ujjwalkarn/Machine-Learning-Tutorials){target="_blank"}
* [Machine Learning in Python](https://github.com/rasbt/python-machine-learning-book-2nd-edition){target="_blank"}
* [120 Data Science Interview Questions](https://github.com/kojino/120-Data-Science-Interview-Questions)
* [Coding Interview Guide](https://github.com/jwasham/coding-interview-university){target="_blank"}
* [Computer Science Links, Lists, and  Resources](https://github.com/sindresorhus/awesome){target="_blank"}
* [Computer Science Papers](https://github.com/papers-we-love/papers-we-love){target="_blank"}
***  
  
## Online Help Forums
* [r/Data Science](https://www.reddit.com/r/datascience/)
* [r/learnmachinelearning](https://www.reddit.com/r/learnmachinelearning/)
* [r/MachineLearning](https://www.reddit.com/r/MachineLearning/)
* [Towards Data Science: Big List of Data Science / Machine Learning Interview Questions](https://towardsdatascience.com/the-big-list-of-ds-ml-interview-resources-2db4f651bd63)
* [Towards Data Science: Mastering the Data Science Interview](https://towardsdatascience.com/mastering-the-data-science-interview-15f9c0a558a7)

***
## Self-Improvement

* [The Pomodoro Method](https://studytime.co.nz/study-advice/why-taking-study-breaks-is-important/)
* [Want to learn a new skill? Take some short breaks](https://www.ninds.nih.gov/News-Events/News-and-Press-Releases/Press-Releases/Want-learn-new-skill-Take-some-short-breaks%20)
* [The 30 Second Habit That Can Have a Big Impact On Your Life](https://www.huffpost.com/entry/the-30-second-habit-that-_b_4808632)
* [Multitasking Damages Your Brain And Career, New Studies Suggest](https://www.forbes.com/sites/travisbradberry/2014/10/08/multitasking-damages-your-brain-and-career-new-studies-suggest/#13fdddd056ee)

***